#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GundamShop.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLShopGundam")]
	public partial class dbQLShopGundamDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertADMIN(ADMIN instance);
    partial void UpdateADMIN(ADMIN instance);
    partial void DeleteADMIN(ADMIN instance);
    partial void InsertCAPDO(CAPDO instance);
    partial void UpdateCAPDO(CAPDO instance);
    partial void DeleteCAPDO(CAPDO instance);
    partial void InsertCTDATHANG(CTDATHANG instance);
    partial void UpdateCTDATHANG(CTDATHANG instance);
    partial void DeleteCTDATHANG(CTDATHANG instance);
    partial void InsertDONDATHANG(DONDATHANG instance);
    partial void UpdateDONDATHANG(DONDATHANG instance);
    partial void DeleteDONDATHANG(DONDATHANG instance);
    partial void InsertGUNDAM(GUNDAM instance);
    partial void UpdateGUNDAM(GUNDAM instance);
    partial void DeleteGUNDAM(GUNDAM instance);
    partial void InsertKHACHHANG(KHACHHANG instance);
    partial void UpdateKHACHHANG(KHACHHANG instance);
    partial void DeleteKHACHHANG(KHACHHANG instance);
    #endregion
		
		public dbQLShopGundamDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["QLShopGundamConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbQLShopGundamDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbQLShopGundamDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbQLShopGundamDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbQLShopGundamDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ADMIN> ADMINs
		{
			get
			{
				return this.GetTable<ADMIN>();
			}
		}
		
		public System.Data.Linq.Table<CAPDO> CAPDOs
		{
			get
			{
				return this.GetTable<CAPDO>();
			}
		}
		
		public System.Data.Linq.Table<CTDATHANG> CTDATHANGs
		{
			get
			{
				return this.GetTable<CTDATHANG>();
			}
		}
		
		public System.Data.Linq.Table<DONDATHANG> DONDATHANGs
		{
			get
			{
				return this.GetTable<DONDATHANG>();
			}
		}
		
		public System.Data.Linq.Table<GUNDAM> GUNDAMs
		{
			get
			{
				return this.GetTable<GUNDAM>();
			}
		}
		
		public System.Data.Linq.Table<KHACHHANG> KHACHHANGs
		{
			get
			{
				return this.GetTable<KHACHHANG>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ADMIN")]
	public partial class ADMIN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaAdmin;
		
		private string _HoTenAdmin;
		
		private string _DiaChiAdmin;
		
		private string _DienThoaiAdmin;
		
		private string _TenDNAdmin;
		
		private string _MatKhauAdmin;
		
		private System.Nullable<System.DateTime> _NgaySinhAdmin;
		
		private System.Nullable<bool> _GioiTinhAdmin;
		
		private string _EmailAdmin;
		
		private System.Nullable<int> _QuyenAdmin;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaAdminChanging(int value);
    partial void OnMaAdminChanged();
    partial void OnHoTenAdminChanging(string value);
    partial void OnHoTenAdminChanged();
    partial void OnDiaChiAdminChanging(string value);
    partial void OnDiaChiAdminChanged();
    partial void OnDienThoaiAdminChanging(string value);
    partial void OnDienThoaiAdminChanged();
    partial void OnTenDNAdminChanging(string value);
    partial void OnTenDNAdminChanged();
    partial void OnMatKhauAdminChanging(string value);
    partial void OnMatKhauAdminChanged();
    partial void OnNgaySinhAdminChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhAdminChanged();
    partial void OnGioiTinhAdminChanging(System.Nullable<bool> value);
    partial void OnGioiTinhAdminChanged();
    partial void OnEmailAdminChanging(string value);
    partial void OnEmailAdminChanged();
    partial void OnQuyenAdminChanging(System.Nullable<int> value);
    partial void OnQuyenAdminChanged();
    #endregion
		
		public ADMIN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaAdmin", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaAdmin
		{
			get
			{
				return this._MaAdmin;
			}
			set
			{
				if ((this._MaAdmin != value))
				{
					this.OnMaAdminChanging(value);
					this.SendPropertyChanging();
					this._MaAdmin = value;
					this.SendPropertyChanged("MaAdmin");
					this.OnMaAdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTenAdmin", DbType="NVarChar(50)")]
		public string HoTenAdmin
		{
			get
			{
				return this._HoTenAdmin;
			}
			set
			{
				if ((this._HoTenAdmin != value))
				{
					this.OnHoTenAdminChanging(value);
					this.SendPropertyChanging();
					this._HoTenAdmin = value;
					this.SendPropertyChanged("HoTenAdmin");
					this.OnHoTenAdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChiAdmin", DbType="NVarChar(50)")]
		public string DiaChiAdmin
		{
			get
			{
				return this._DiaChiAdmin;
			}
			set
			{
				if ((this._DiaChiAdmin != value))
				{
					this.OnDiaChiAdminChanging(value);
					this.SendPropertyChanging();
					this._DiaChiAdmin = value;
					this.SendPropertyChanged("DiaChiAdmin");
					this.OnDiaChiAdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoaiAdmin", DbType="VarChar(10)")]
		public string DienThoaiAdmin
		{
			get
			{
				return this._DienThoaiAdmin;
			}
			set
			{
				if ((this._DienThoaiAdmin != value))
				{
					this.OnDienThoaiAdminChanging(value);
					this.SendPropertyChanging();
					this._DienThoaiAdmin = value;
					this.SendPropertyChanged("DienThoaiAdmin");
					this.OnDienThoaiAdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDNAdmin", DbType="VarChar(15)")]
		public string TenDNAdmin
		{
			get
			{
				return this._TenDNAdmin;
			}
			set
			{
				if ((this._TenDNAdmin != value))
				{
					this.OnTenDNAdminChanging(value);
					this.SendPropertyChanging();
					this._TenDNAdmin = value;
					this.SendPropertyChanged("TenDNAdmin");
					this.OnTenDNAdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhauAdmin", DbType="VarChar(15)")]
		public string MatKhauAdmin
		{
			get
			{
				return this._MatKhauAdmin;
			}
			set
			{
				if ((this._MatKhauAdmin != value))
				{
					this.OnMatKhauAdminChanging(value);
					this.SendPropertyChanging();
					this._MatKhauAdmin = value;
					this.SendPropertyChanged("MatKhauAdmin");
					this.OnMatKhauAdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinhAdmin", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> NgaySinhAdmin
		{
			get
			{
				return this._NgaySinhAdmin;
			}
			set
			{
				if ((this._NgaySinhAdmin != value))
				{
					this.OnNgaySinhAdminChanging(value);
					this.SendPropertyChanging();
					this._NgaySinhAdmin = value;
					this.SendPropertyChanged("NgaySinhAdmin");
					this.OnNgaySinhAdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinhAdmin", DbType="Bit")]
		public System.Nullable<bool> GioiTinhAdmin
		{
			get
			{
				return this._GioiTinhAdmin;
			}
			set
			{
				if ((this._GioiTinhAdmin != value))
				{
					this.OnGioiTinhAdminChanging(value);
					this.SendPropertyChanging();
					this._GioiTinhAdmin = value;
					this.SendPropertyChanged("GioiTinhAdmin");
					this.OnGioiTinhAdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailAdmin", DbType="VarChar(50)")]
		public string EmailAdmin
		{
			get
			{
				return this._EmailAdmin;
			}
			set
			{
				if ((this._EmailAdmin != value))
				{
					this.OnEmailAdminChanging(value);
					this.SendPropertyChanging();
					this._EmailAdmin = value;
					this.SendPropertyChanged("EmailAdmin");
					this.OnEmailAdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuyenAdmin", DbType="Int")]
		public System.Nullable<int> QuyenAdmin
		{
			get
			{
				return this._QuyenAdmin;
			}
			set
			{
				if ((this._QuyenAdmin != value))
				{
					this.OnQuyenAdminChanging(value);
					this.SendPropertyChanging();
					this._QuyenAdmin = value;
					this.SendPropertyChanged("QuyenAdmin");
					this.OnQuyenAdminChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CAPDO")]
	public partial class CAPDO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaCD;
		
		private string _TenCapDo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaCDChanging(int value);
    partial void OnMaCDChanged();
    partial void OnTenCapDoChanging(string value);
    partial void OnTenCapDoChanged();
    #endregion
		
		public CAPDO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCD", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaCD
		{
			get
			{
				return this._MaCD;
			}
			set
			{
				if ((this._MaCD != value))
				{
					this.OnMaCDChanging(value);
					this.SendPropertyChanging();
					this._MaCD = value;
					this.SendPropertyChanged("MaCD");
					this.OnMaCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenCapDo", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenCapDo
		{
			get
			{
				return this._TenCapDo;
			}
			set
			{
				if ((this._TenCapDo != value))
				{
					this.OnTenCapDoChanging(value);
					this.SendPropertyChanging();
					this._TenCapDo = value;
					this.SendPropertyChanged("TenCapDo");
					this.OnTenCapDoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CTDATHANG")]
	public partial class CTDATHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SoDH;
		
		private int _MaGundam;
		
		private System.Nullable<int> _SoLuong;
		
		private System.Nullable<decimal> _DonGia;
		
		private System.Nullable<decimal> _ThanhTien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSoDHChanging(int value);
    partial void OnSoDHChanged();
    partial void OnMaGundamChanging(int value);
    partial void OnMaGundamChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    partial void OnDonGiaChanging(System.Nullable<decimal> value);
    partial void OnDonGiaChanged();
    partial void OnThanhTienChanging(System.Nullable<decimal> value);
    partial void OnThanhTienChanged();
    #endregion
		
		public CTDATHANG()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDH", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int SoDH
		{
			get
			{
				return this._SoDH;
			}
			set
			{
				if ((this._SoDH != value))
				{
					this.OnSoDHChanging(value);
					this.SendPropertyChanging();
					this._SoDH = value;
					this.SendPropertyChanged("SoDH");
					this.OnSoDHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGundam", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaGundam
		{
			get
			{
				return this._MaGundam;
			}
			set
			{
				if ((this._MaGundam != value))
				{
					this.OnMaGundamChanging(value);
					this.SendPropertyChanging();
					this._MaGundam = value;
					this.SendPropertyChanged("MaGundam");
					this.OnMaGundamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="Decimal(9,2)")]
		public System.Nullable<decimal> DonGia
		{
			get
			{
				return this._DonGia;
			}
			set
			{
				if ((this._DonGia != value))
				{
					this.OnDonGiaChanging(value);
					this.SendPropertyChanging();
					this._DonGia = value;
					this.SendPropertyChanged("DonGia");
					this.OnDonGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThanhTien", AutoSync=AutoSync.Always, DbType="Decimal(20,2)", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<decimal> ThanhTien
		{
			get
			{
				return this._ThanhTien;
			}
			set
			{
				if ((this._ThanhTien != value))
				{
					this.OnThanhTienChanging(value);
					this.SendPropertyChanging();
					this._ThanhTien = value;
					this.SendPropertyChanged("ThanhTien");
					this.OnThanhTienChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DONDATHANG")]
	public partial class DONDATHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SoDH;
		
		private System.Nullable<int> _MaKH;
		
		private System.Nullable<System.DateTime> _NgayDH;
		
		private System.Nullable<decimal> _TriGia;
		
		private System.Nullable<bool> _DaGiao;
		
		private System.Nullable<System.DateTime> _NgayGiaoHang;
		
		private string _TenNguoiNhan;
		
		private string _DiaChiNhan;
		
		private string _DienThoaiNhan;
		
		private System.Nullable<bool> _HTThanhToan;
		
		private System.Nullable<bool> _HTGiaoHang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSoDHChanging(int value);
    partial void OnSoDHChanged();
    partial void OnMaKHChanging(System.Nullable<int> value);
    partial void OnMaKHChanged();
    partial void OnNgayDHChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayDHChanged();
    partial void OnTriGiaChanging(System.Nullable<decimal> value);
    partial void OnTriGiaChanged();
    partial void OnDaGiaoChanging(System.Nullable<bool> value);
    partial void OnDaGiaoChanged();
    partial void OnNgayGiaoHangChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayGiaoHangChanged();
    partial void OnTenNguoiNhanChanging(string value);
    partial void OnTenNguoiNhanChanged();
    partial void OnDiaChiNhanChanging(string value);
    partial void OnDiaChiNhanChanged();
    partial void OnDienThoaiNhanChanging(string value);
    partial void OnDienThoaiNhanChanged();
    partial void OnHTThanhToanChanging(System.Nullable<bool> value);
    partial void OnHTThanhToanChanged();
    partial void OnHTGiaoHangChanging(System.Nullable<bool> value);
    partial void OnHTGiaoHangChanged();
    #endregion
		
		public DONDATHANG()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDH", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SoDH
		{
			get
			{
				return this._SoDH;
			}
			set
			{
				if ((this._SoDH != value))
				{
					this.OnSoDHChanging(value);
					this.SendPropertyChanging();
					this._SoDH = value;
					this.SendPropertyChanged("SoDH");
					this.OnSoDHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="Int")]
		public System.Nullable<int> MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDH", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> NgayDH
		{
			get
			{
				return this._NgayDH;
			}
			set
			{
				if ((this._NgayDH != value))
				{
					this.OnNgayDHChanging(value);
					this.SendPropertyChanging();
					this._NgayDH = value;
					this.SendPropertyChanged("NgayDH");
					this.OnNgayDHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TriGia", DbType="Money")]
		public System.Nullable<decimal> TriGia
		{
			get
			{
				return this._TriGia;
			}
			set
			{
				if ((this._TriGia != value))
				{
					this.OnTriGiaChanging(value);
					this.SendPropertyChanging();
					this._TriGia = value;
					this.SendPropertyChanged("TriGia");
					this.OnTriGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaGiao", DbType="Bit")]
		public System.Nullable<bool> DaGiao
		{
			get
			{
				return this._DaGiao;
			}
			set
			{
				if ((this._DaGiao != value))
				{
					this.OnDaGiaoChanging(value);
					this.SendPropertyChanging();
					this._DaGiao = value;
					this.SendPropertyChanged("DaGiao");
					this.OnDaGiaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayGiaoHang", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> NgayGiaoHang
		{
			get
			{
				return this._NgayGiaoHang;
			}
			set
			{
				if ((this._NgayGiaoHang != value))
				{
					this.OnNgayGiaoHangChanging(value);
					this.SendPropertyChanging();
					this._NgayGiaoHang = value;
					this.SendPropertyChanged("NgayGiaoHang");
					this.OnNgayGiaoHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNguoiNhan", DbType="VarChar(50)")]
		public string TenNguoiNhan
		{
			get
			{
				return this._TenNguoiNhan;
			}
			set
			{
				if ((this._TenNguoiNhan != value))
				{
					this.OnTenNguoiNhanChanging(value);
					this.SendPropertyChanging();
					this._TenNguoiNhan = value;
					this.SendPropertyChanged("TenNguoiNhan");
					this.OnTenNguoiNhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChiNhan", DbType="NVarChar(50)")]
		public string DiaChiNhan
		{
			get
			{
				return this._DiaChiNhan;
			}
			set
			{
				if ((this._DiaChiNhan != value))
				{
					this.OnDiaChiNhanChanging(value);
					this.SendPropertyChanging();
					this._DiaChiNhan = value;
					this.SendPropertyChanged("DiaChiNhan");
					this.OnDiaChiNhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoaiNhan", DbType="VarChar(15)")]
		public string DienThoaiNhan
		{
			get
			{
				return this._DienThoaiNhan;
			}
			set
			{
				if ((this._DienThoaiNhan != value))
				{
					this.OnDienThoaiNhanChanging(value);
					this.SendPropertyChanging();
					this._DienThoaiNhan = value;
					this.SendPropertyChanged("DienThoaiNhan");
					this.OnDienThoaiNhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HTThanhToan", DbType="Bit")]
		public System.Nullable<bool> HTThanhToan
		{
			get
			{
				return this._HTThanhToan;
			}
			set
			{
				if ((this._HTThanhToan != value))
				{
					this.OnHTThanhToanChanging(value);
					this.SendPropertyChanging();
					this._HTThanhToan = value;
					this.SendPropertyChanged("HTThanhToan");
					this.OnHTThanhToanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HTGiaoHang", DbType="Bit")]
		public System.Nullable<bool> HTGiaoHang
		{
			get
			{
				return this._HTGiaoHang;
			}
			set
			{
				if ((this._HTGiaoHang != value))
				{
					this.OnHTGiaoHangChanging(value);
					this.SendPropertyChanging();
					this._HTGiaoHang = value;
					this.SendPropertyChanged("HTGiaoHang");
					this.OnHTGiaoHangChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GUNDAM")]
	public partial class GUNDAM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaGundam;
		
		private string _TenGundam;
		
		private string _DonViTinh;
		
		private System.Nullable<decimal> _DonGia;
		
		private string _MoTa;
		
		private string _HinhMinhHoa;
		
		private System.Nullable<int> _MaCD;
		
		private System.Nullable<System.DateTime> _NgaySanXuat;
		
		private System.Nullable<int> _SoLuongBan;
		
		private System.Nullable<int> _SoLanXem;
		
		private System.Nullable<int> _SoLuongConLai;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaGundamChanging(int value);
    partial void OnMaGundamChanged();
    partial void OnTenGundamChanging(string value);
    partial void OnTenGundamChanged();
    partial void OnDonViTinhChanging(string value);
    partial void OnDonViTinhChanged();
    partial void OnDonGiaChanging(System.Nullable<decimal> value);
    partial void OnDonGiaChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    partial void OnHinhMinhHoaChanging(string value);
    partial void OnHinhMinhHoaChanged();
    partial void OnMaCDChanging(System.Nullable<int> value);
    partial void OnMaCDChanged();
    partial void OnNgaySanXuatChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySanXuatChanged();
    partial void OnSoLuongBanChanging(System.Nullable<int> value);
    partial void OnSoLuongBanChanged();
    partial void OnSoLanXemChanging(System.Nullable<int> value);
    partial void OnSoLanXemChanged();
    partial void OnSoLuongConLaiChanging(System.Nullable<int> value);
    partial void OnSoLuongConLaiChanged();
    #endregion
		
		public GUNDAM()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGundam", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaGundam
		{
			get
			{
				return this._MaGundam;
			}
			set
			{
				if ((this._MaGundam != value))
				{
					this.OnMaGundamChanging(value);
					this.SendPropertyChanging();
					this._MaGundam = value;
					this.SendPropertyChanged("MaGundam");
					this.OnMaGundamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenGundam", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenGundam
		{
			get
			{
				return this._TenGundam;
			}
			set
			{
				if ((this._TenGundam != value))
				{
					this.OnTenGundamChanging(value);
					this.SendPropertyChanging();
					this._TenGundam = value;
					this.SendPropertyChanged("TenGundam");
					this.OnTenGundamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonViTinh", DbType="NVarChar(50)")]
		public string DonViTinh
		{
			get
			{
				return this._DonViTinh;
			}
			set
			{
				if ((this._DonViTinh != value))
				{
					this.OnDonViTinhChanging(value);
					this.SendPropertyChanging();
					this._DonViTinh = value;
					this.SendPropertyChanged("DonViTinh");
					this.OnDonViTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="Money")]
		public System.Nullable<decimal> DonGia
		{
			get
			{
				return this._DonGia;
			}
			set
			{
				if ((this._DonGia != value))
				{
					this.OnDonGiaChanging(value);
					this.SendPropertyChanging();
					this._DonGia = value;
					this.SendPropertyChanged("DonGia");
					this.OnDonGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhMinhHoa", DbType="VarChar(50)")]
		public string HinhMinhHoa
		{
			get
			{
				return this._HinhMinhHoa;
			}
			set
			{
				if ((this._HinhMinhHoa != value))
				{
					this.OnHinhMinhHoaChanging(value);
					this.SendPropertyChanging();
					this._HinhMinhHoa = value;
					this.SendPropertyChanged("HinhMinhHoa");
					this.OnHinhMinhHoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCD", DbType="Int")]
		public System.Nullable<int> MaCD
		{
			get
			{
				return this._MaCD;
			}
			set
			{
				if ((this._MaCD != value))
				{
					this.OnMaCDChanging(value);
					this.SendPropertyChanging();
					this._MaCD = value;
					this.SendPropertyChanged("MaCD");
					this.OnMaCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySanXuat", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> NgaySanXuat
		{
			get
			{
				return this._NgaySanXuat;
			}
			set
			{
				if ((this._NgaySanXuat != value))
				{
					this.OnNgaySanXuatChanging(value);
					this.SendPropertyChanging();
					this._NgaySanXuat = value;
					this.SendPropertyChanged("NgaySanXuat");
					this.OnNgaySanXuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongBan", DbType="Int")]
		public System.Nullable<int> SoLuongBan
		{
			get
			{
				return this._SoLuongBan;
			}
			set
			{
				if ((this._SoLuongBan != value))
				{
					this.OnSoLuongBanChanging(value);
					this.SendPropertyChanging();
					this._SoLuongBan = value;
					this.SendPropertyChanged("SoLuongBan");
					this.OnSoLuongBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLanXem", DbType="Int")]
		public System.Nullable<int> SoLanXem
		{
			get
			{
				return this._SoLanXem;
			}
			set
			{
				if ((this._SoLanXem != value))
				{
					this.OnSoLanXemChanging(value);
					this.SendPropertyChanging();
					this._SoLanXem = value;
					this.SendPropertyChanged("SoLanXem");
					this.OnSoLanXemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongConLai", DbType="Int")]
		public System.Nullable<int> SoLuongConLai
		{
			get
			{
				return this._SoLuongConLai;
			}
			set
			{
				if ((this._SoLuongConLai != value))
				{
					this.OnSoLuongConLaiChanging(value);
					this.SendPropertyChanging();
					this._SoLuongConLai = value;
					this.SendPropertyChanged("SoLuongConLai");
					this.OnSoLuongConLaiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KHACHHANG")]
	public partial class KHACHHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaKH;
		
		private string _HoTenKH;
		
		private string _DiaChiKH;
		
		private string _DienThoaiKH;
		
		private string _TenDN;
		
		private string _MatKhau;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private System.Nullable<bool> _GioiTinh;
		
		private string _Email;
		
		private System.Nullable<bool> _DaDuyet;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKHChanging(int value);
    partial void OnMaKHChanged();
    partial void OnHoTenKHChanging(string value);
    partial void OnHoTenKHChanged();
    partial void OnDiaChiKHChanging(string value);
    partial void OnDiaChiKHChanged();
    partial void OnDienThoaiKHChanging(string value);
    partial void OnDienThoaiKHChanged();
    partial void OnTenDNChanging(string value);
    partial void OnTenDNChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnGioiTinhChanging(System.Nullable<bool> value);
    partial void OnGioiTinhChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnDaDuyetChanging(System.Nullable<bool> value);
    partial void OnDaDuyetChanged();
    #endregion
		
		public KHACHHANG()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTenKH", DbType="NVarChar(50)")]
		public string HoTenKH
		{
			get
			{
				return this._HoTenKH;
			}
			set
			{
				if ((this._HoTenKH != value))
				{
					this.OnHoTenKHChanging(value);
					this.SendPropertyChanging();
					this._HoTenKH = value;
					this.SendPropertyChanged("HoTenKH");
					this.OnHoTenKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChiKH", DbType="NVarChar(50)")]
		public string DiaChiKH
		{
			get
			{
				return this._DiaChiKH;
			}
			set
			{
				if ((this._DiaChiKH != value))
				{
					this.OnDiaChiKHChanging(value);
					this.SendPropertyChanging();
					this._DiaChiKH = value;
					this.SendPropertyChanged("DiaChiKH");
					this.OnDiaChiKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoaiKH", DbType="VarChar(10)")]
		public string DienThoaiKH
		{
			get
			{
				return this._DienThoaiKH;
			}
			set
			{
				if ((this._DienThoaiKH != value))
				{
					this.OnDienThoaiKHChanging(value);
					this.SendPropertyChanging();
					this._DienThoaiKH = value;
					this.SendPropertyChanged("DienThoaiKH");
					this.OnDienThoaiKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDN", DbType="VarChar(15)")]
		public string TenDN
		{
			get
			{
				return this._TenDN;
			}
			set
			{
				if ((this._TenDN != value))
				{
					this.OnTenDNChanging(value);
					this.SendPropertyChanging();
					this._TenDN = value;
					this.SendPropertyChanged("TenDN");
					this.OnTenDNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="VarChar(15)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="Bit")]
		public System.Nullable<bool> GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaDuyet", DbType="Bit")]
		public System.Nullable<bool> DaDuyet
		{
			get
			{
				return this._DaDuyet;
			}
			set
			{
				if ((this._DaDuyet != value))
				{
					this.OnDaDuyetChanging(value);
					this.SendPropertyChanging();
					this._DaDuyet = value;
					this.SendPropertyChanged("DaDuyet");
					this.OnDaDuyetChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
